export let Category = [
    {"name": "General Knowledge", "value": "9", "icon": "fa fa-lightbulb"},
    {"name": "Books", "value": "10", "icon": "fa fa-book"},
    {"name": "Film", "value": "11", "icon": "fa fa-film"},
    {"name": "Music", "value": "12", "icon": "fa fa-music"},
    {"name": "Musicals & Theatres", "value": "13", "icon": "fa fa-theater-masks"},
    {"name": "Television", "value": "14", "icon": "fa fa-tv"},
    {"name": "Video Games", "value": "15", "icon": "fa fa-gamepad"},
    {"name": "Board Games", "value": "16", "icon": "fa fa-chess-board"},
    {"name": "Science & Nature", "value": "17", "icon": "fa fa-leaf"},
    {"name": "Computers", "value": "18", "icon": "fa fa-desktop"},
    {"name": "Mathematics", "value": "19", "icon": "fa fa-square-root-alt"},
    {"name": "Mythology", "value": "20", "icon": "fa fa-dragon"},
    {"name": "Sports", "value": "21", "icon": "fa fa-football-ball"},
    {"name": "Geography", "value": "22", "icon": "fa fa-globe"},
    {"name": "History", "value": "23", "icon": "fa fa-landmark"},
    {"name": "Politics", "value": "24", "icon": "fa fa-balance-scale"},
    {"name": "Art", "value": "25", "icon": "fa fa-paint-brush"},
    {"name": "Celebrities", "value": "26", "icon": "fa fa-star"},
    {"name": "Animals", "value": "27", "icon": "fa fa-paw"},
    {"name": "Vehicles", "value": "28", "icon": "fa fa-car"},
    {"name": "Comics", "value": "29", "icon": "fa fa-book-open"},
    {"name": "Gadgets", "value": "30", "icon": "fa fa-microchip"},
    {"name": "Japanese Anime & Manga", "value": "31", "icon": "fa fa-heart"},
    {"name": "Cartoon & Animations", "value": "32", "icon": "fa fa-smile"}
]
